language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer install --dev --no-interaction

script:
  - cp tests/config.php.dist tests/config.php
  - make test

after_script:
  - vendor/bin/coveralls -v
